apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-app
  labels:
    app: farm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farm-app
  template: # Template is the object that describes the pod that will be created if needed.
    metadata:
      labels:
        app: farm-app
    spec:
      containers: # List of containers that make up the pod.
      - name: farm-app
        image: vncnttejas/farm-app
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: "0.4"
            memory: "128Mi"
          requests:
            cpu: "0.2"
            memory: "64Mi"
        env: # List of environment variables to set in the container.
        - name: APP_PORT
          value: '3000'
        - name: "LOG_LEVEL"
          value: "info"
        - name: "LOG_NAME"
          value: "farm-app"
        - name: "NODE_ENV"
          value: "dev"
        - name: "NODE_HOST"
          value: "0.0.0.0"
        - name: "MONGO_URI"
          valueFrom:
            secretKeyRef:
              name: farm-app-release
              key: "mongo-uri"
---
apiVersion: v1
kind: Service
metadata:
  name: farm-app
  labels:
    app: farm-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: farm-app
